class_name FlockErrorCode

const UNKNOWN := 0

const ANALYTICS_CURRENCY_NOT_FOUND := 1
const ANALYTICS_PLAYER_NOT_FOUND := 2
const ANALYTICS_SESSION_NOT_FOUND := 3

const ASSET_ASSET_NOT_FOUND := 10

const GAME_GAME_NOT_FOUND := 20
const GAME_MISSING_STUDIO_ID := 21

const GAME_COMMAND_ACHIEVEMENT_NOT_FOUND := 30
const GAME_COMMAND_CURRENCY_NOT_FOUND := 31
const GAME_COMMAND_INVALID_AMOUNT := 32
const GAME_COMMAND_NOT_A_WALLET := 33
const GAME_COMMAND_NOT_AN_ACHIEVEMENT_RECORD := 34
const GAME_COMMAND_PLAYER_DATA_NOT_FOUND := 35
const GAME_COMMAND_PLAYER_DATA_NOT_LINKED_TO_TEMPLATE := 36
const GAME_COMMAND_PLAYER_TEMPLATE_NOT_FOUND := 37
const GAME_COMMAND_TEMPLATE_VALIDATION_FAILED := 38

const GAME_CONFIG_CONFIG_NOT_FOUND := 40
const GAME_CONFIG_FEATURE_CONFIG_NOT_FOUND := 41
const GAME_CONFIG_INVALID_TAG := 42
const GAME_CONFIG_PLAYER_NO_GAME_VERSION := 43
const GAME_CONFIG_PLAYER_NOT_FOUND := 44

const GAME_PATCH_GAME_CONFIG_NOT_FOUND := 50
const GAME_PATCH_PATCH_NOT_FOUND := 51

const GAME_VERSION_BY_NAME_NOT_FOUND := 60
const GAME_VERSION_NOT_FOUND := 61

const LOG_EVENT_GAME_NOT_FOUND := 70

const PLAYER_APPLE_ACCOUNT_ALREADY_REGISTERED := 80
const PLAYER_DEVICE_ALREADY_REGISTERED := 81
const PLAYER_EMAIL_ALREADY_REGISTERED := 82
const PLAYER_GAME_JWK_NOT_CONFIGURED := 83
const PLAYER_GAME_VERSION_ID_REQUIRED := 84
const PLAYER_GOOGLE_ACCOUNT_ALREADY_REGISTERED := 85
const PLAYER_INVALID_DEVICE_REGISTRATION_REQUEST := 86
const PLAYER_INVALID_LOGIN_CREDENTIALS := 87
const PLAYER_INVALID_REFRESH_TOKEN := 88
const PLAYER_INVALID_REGISTRATION_REQUEST := 89
const PLAYER_INVALID_RESET_CODE := 90
const PLAYER_INVALID_VERIFICATION_CODE := 91
const PLAYER_NAME_ALREADY_REGISTERED := 92
const PLAYER_NO_EMAIL_ACCOUNT := 93
const PLAYER_OAUTH_FAILED := 94
const PLAYER_PLAYER_NOT_FOUND := 95
const PLAYER_STEAM_ACCOUNT_ALREADY_REGISTERED := 96

const PLAYER_BAN_PLAYER_NOT_FOUND := 100

const PLAYER_DATA_NOT_FOUND := 110
const PLAYER_DATA_PLAYER_NOT_FOUND := 111

const PLAYER_INVENTORY_PLAYER_NOT_FOUND := 120

const PLAYER_TEMPLATE_NOT_FOUND := 130
const PLAYER_TEMPLATE_NOT_FOUND_BY_NAME := 131

const SHOP_CURRENCY_NOT_HELD := 140
const SHOP_CURRENCY_TEMPLATE_NOT_FOUND := 141
const SHOP_INSUFFICIENT_FUNDS := 142
const SHOP_ITEM_NOT_FOUND := 143
const SHOP_PLAYER_NOT_FOUND := 144
const SHOP_SHOP_NOT_FOUND := 145
const SHOP_WALLET_NOT_FOUND := 146

const SHOP_ITEM_SHOP_ITEM_NOT_FOUND := 150
const SHOP_ITEM_SHOP_NOT_FOUND := 151
